<<<<<<< HEAD
# Generated by Django 5.0.14 on 2025-05-19 16:16
=======
# Generated by Django 5.0.14 on 2025-04-27 18:33
>>>>>>> 3d4f397a324450a04a362f7d9feb23d25a1b81ea

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('cursos', '0001_initial'),
        ('estudiantes', '0001_initial'),
        ('usuarios', '0001_initial'),
=======
        ('docentes', '0001_initial'),
        ('inscripciones', '0001_initial'),
>>>>>>> 3d4f397a324450a04a362f7d9feb23d25a1b81ea
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
<<<<<<< HEAD
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('justificado', 'Justificado')], max_length=20)),
                ('permiso_solicitado', models.BooleanField(default=False)),
                ('archivo_justificacion', models.FileField(blank=True, null=True, upload_to='documentacion/asistencias/')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
                ('justificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
=======
                ('estado', models.CharField(max_length=20)),
                ('id_docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.CASCADE, to='docentes.docente')),
                ('id_inscripcion', models.ForeignKey(db_column='id_inscripcion', on_delete=django.db.models.deletion.CASCADE, to='inscripciones.inscripcion')),
            ],
            options={
                'db_table': 'asistencia',
            },
>>>>>>> 3d4f397a324450a04a362f7d9feb23d25a1b81ea
        ),
    ]
