# Generated by Django 5.0.14 on 2025-05-19 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('ci', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('regular', 'Regular'), ('tecnico', 'Técnico')], max_length=20)),
                ('grupo', models.CharField(blank=True, choices=[('Sweet', 'Sweet'), ('Smart', 'Smart'), ('Teens', 'Teens')], max_length=20, null=True)),
                ('colegio_universidad', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('archivo_documentacion', models.FileField(blank=True, null=True, upload_to='documentacion/estudiantes/')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.padre')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
