# Generated by Django 5.0.14 on 2025-04-16 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'asignatura',
            },
        ),
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('cargo', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'directivo',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('fecha_contrato', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'docente',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('colegio', models.CharField(max_length=100)),
                ('grupo', models.CharField(max_length=50)),
                ('dias', models.CharField(max_length=50)),
                ('hora', models.CharField(max_length=50)),
                ('modalidad', models.CharField(max_length=50)),
                ('medio_referencia', models.CharField(max_length=100)),
                ('motivo_estudio', models.TextField(blank=True, null=True)),
                ('archivo_formulario', models.FileField(blank=True, null=True, upload_to='formularios/')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('horario_trabajo', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'secretaria',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=50)),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.CASCADE, to='core.asignatura')),
                ('directivo', models.ForeignKey(db_column='id_directivo', on_delete=django.db.models.deletion.CASCADE, to='core.directivo')),
                ('estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, to='core.estudiante')),
                ('secretaria', models.ForeignKey(db_column='id_secretaria', on_delete=django.db.models.deletion.CASCADE, to='core.secretaria')),
            ],
            options={
                'db_table': 'inscripcion',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.CASCADE, to='core.docente')),
                ('inscripcion', models.ForeignKey(db_column='id_inscripcion', on_delete=django.db.models.deletion.CASCADE, to='core.inscripcion')),
            ],
            options={
                'db_table': 'asistencia',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcial1', models.FloatField()),
                ('parcial2', models.FloatField()),
                ('examen_final', models.FloatField()),
                ('promedio', models.FloatField()),
                ('docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.CASCADE, to='core.docente')),
                ('inscripcion', models.ForeignKey(db_column='id_inscripcion', on_delete=django.db.models.deletion.CASCADE, to='core.inscripcion')),
            ],
            options={
                'db_table': 'nota',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('lugar_trabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_trabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.OneToOneField(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'tutor',
            },
        ),
        migrations.AddField(
            model_name='secretaria',
            name='usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AddField(
            model_name='docente',
            name='usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.AddField(
            model_name='directivo',
            name='usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='VarkResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prueba', models.DateField()),
                ('visual', models.FloatField()),
                ('auditivo', models.FloatField()),
                ('lectura', models.FloatField()),
                ('kinestesico', models.FloatField()),
                ('estilo_predominante', models.CharField(max_length=50)),
                ('estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, to='core.estudiante')),
            ],
            options={
                'db_table': 'vark_resultado',
            },
        ),
        migrations.CreateModel(
            name='DocenteAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.CASCADE, to='core.asignatura')),
                ('docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.CASCADE, to='core.docente')),
            ],
            options={
                'db_table': 'docente_asignatura',
                'unique_together': {('docente', 'asignatura')},
            },
        ),
        migrations.CreateModel(
            name='TieneTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=50)),
                ('estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, to='core.estudiante')),
                ('tutor', models.ForeignKey(db_column='id_tutor', on_delete=django.db.models.deletion.CASCADE, to='core.tutor')),
            ],
            options={
                'db_table': 'tiene_tutor',
                'unique_together': {('estudiante', 'tutor')},
            },
        ),
    ]
