# Generated by Django 5.0.14 on 2025-04-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='celular_referencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='clases_particulares',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='correo_referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='estudios_ingles_previos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='firmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='institucion_actual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='material_entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='recibido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_estudiante',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('profesional', 'Profesional'), ('independiente', 'Independiente')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_inscripcion',
            field=models.CharField(choices=[('anual', 'Anual'), ('vacacional', 'Vacacional'), ('particular', 'Clases particulares'), ('becado', 'Becado')], default='anual', max_length=20),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grupo',
            field=models.CharField(blank=True, choices=[('sweet', 'Sweet'), ('smart', 'Smart'), ('teens', 'Teens'), ('otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='motivo_estudio',
            field=models.CharField(blank=True, choices=[('academico', 'Académico'), ('viaje', 'Viaje'), ('laboral', 'Laboral')], max_length=20, null=True),
        ),
    ]
