<<<<<<< HEAD
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from dotenv import load_dotenv
load_dotenv()

from pathlib import Path

print("DEBUG DB_ENGINE:", os.getenv("DB_ENGINE"))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%wwab50a9ek9m$=17eneo89j^8t44x92ctdy@ppwi!m5#obrju'

# SECURITY WARNING: don't run with debug turned on in production!
=======
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-szt(26&cmzc011qr-0raq!0tm0#d-n&sp31urxs3^_hdyc+t(6'

>>>>>>> 3d4f397a324450a04a362f7d9feb23d25a1b81ea
DEBUG = True

ALLOWED_HOSTS = []

<<<<<<< HEAD

# Application definition

=======
>>>>>>> 3d4f397a324450a04a362f7d9feb23d25a1b81ea
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
    'django_extensions',
    # Apps personalizadas
    'apps.usuarios',
    'apps.estudiantes',
    'apps.asistencia',
    'apps.cursos',
    'apps.notas',
    'apps.publicaciones',
    'apps.vark',
    'apps.publico',    
=======
    'widget_tweaks',  
    'apps.usuarios',
    'apps.estudiantes',
    'apps.tutores',
    'apps.docentes',
    'apps.secretarias',
    'apps.directivos',
    'apps.asignaturas',
    'apps.inscripciones',
    'apps.notas',
    'apps.asistencia',
    'apps.vark',
    'apps.publico',
>>>>>>> 3d4f397a324450a04a362f7d9feb23d25a1b81ea
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
<<<<<<< HEAD
        'DIRS': [
    BASE_DIR / 'apps' / 'usuarios' / 'templates',
    BASE_DIR / 'apps' / 'publico' / 'templates',
    BASE_DIR / 'apps' / 'estudiantes' / 'templates',
],

=======
        'DIRS': [BASE_DIR / 'apps' / 'publico' / 'templates'],
>>>>>>> 3d4f397a324450a04a362f7d9feb23d25a1b81ea
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


<<<<<<< HEAD

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE'), 
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER') or '',
        'PASSWORD': os.getenv('DB_PASSWORD') or '',
        'HOST': os.getenv('DB_HOST'),
        'PORT': '',
        'OPTIONS': {
            'driver': os.getenv('DB_DRIVER'),
            'trusted_connection': 'yes',
            'extra_params': 'TrustServerCertificate=yes;'
=======
WSGI_APPLICATION = 'config.wsgi.application'



""""
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'englishclub',
        'HOST': 'DENIL\\SQLEXPRESS',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'trusted_connection': 'yes',
        },
    }
}
"""

#BASE DE DATOS DE AILYN
"""
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'englishclub',
        'HOST': 'DESKTOP-RI7UI8N\\SQLEXPRESS',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'trusted_connection': 'yes',
        },
    }
}
"""

#BASE DE DATOS MARIOLY

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'englishclub',
        'HOST': 'LAPTOP-M4R1\\SQLEXPRESS',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'trusted_connection': 'yes',
>>>>>>> 3d4f397a324450a04a362f7d9feb23d25a1b81ea
        },
    }
}


<<<<<<< HEAD



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
=======
#BASE DE DATOS DE LIMBER
"""
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'englishclub',
        'HOST': 'LINO\\SQLEXPRESS',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'trusted_connection': 'yes',
        },
    }
}
"""
>>>>>>> 3d4f397a324450a04a362f7d9feb23d25a1b81ea

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

<<<<<<< HEAD

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [ BASE_DIR / 'apps' / 'publico' / 'static' ]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
=======
LANGUAGE_CODE = 'es-bo'

TIME_ZONE = 'America/La_Paz'

USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'

# es para manejar archivos estaticos como esta en la raiz static importante no borrar
STATICFILES_DIRS = [BASE_DIR / 'static']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
>>>>>>> 3d4f397a324450a04a362f7d9feb23d25a1b81ea
