# Generated by Django 4.2.11 on 2025-05-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaladministrativo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
