<<<<<<< HEAD
# Generated by Django 5.0.14 on 2025-05-19 16:16
=======
# Generated by Django 5.0.14 on 2025-04-27 18:33
>>>>>>> 3d4f397a324450a04a362f7d9feb23d25a1b81ea

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
<<<<<<< HEAD
        ('usuarios', '0001_initial'),
=======
>>>>>>> 3d4f397a324450a04a362f7d9feb23d25a1b81ea
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='ResultadoVARK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_dominante', models.CharField(max_length=20)),
                ('gestion', models.CharField(max_length=10)),
                ('origen', models.CharField(choices=[('padre', 'Padre'), ('directivo', 'Directivo'), ('estudiante_tecnico', 'Estudiante Técnico')], max_length=20)),
                ('resultado_sql_id', models.CharField(max_length=50)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
                ('registrado_por_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.padre')),
                ('registrado_por_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.personaladministrativo')),
            ],
=======
            name='VarkResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prueba', models.DateField()),
                ('visual', models.FloatField()),
                ('auditivo', models.FloatField()),
                ('lectura', models.FloatField()),
                ('kinestesico', models.FloatField()),
                ('estilo_predominante', models.CharField(max_length=50)),
                ('id_estudiante', models.OneToOneField(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
            ],
            options={
                'db_table': 'vark_resultado',
            },
>>>>>>> 3d4f397a324450a04a362f7d9feb23d25a1b81ea
        ),
    ]
