# Generated by Django 5.0.14 on 2025-05-19 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoVARK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_dominante', models.CharField(max_length=20)),
                ('gestion', models.CharField(max_length=10)),
                ('origen', models.CharField(choices=[('padre', 'Padre'), ('directivo', 'Directivo'), ('estudiante_tecnico', 'Estudiante Técnico')], max_length=20)),
                ('resultado_sql_id', models.CharField(max_length=50)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
                ('registrado_por_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.padre')),
                ('registrado_por_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.personaladministrativo')),
            ],
        ),
    ]
