<<<<<<< HEAD
# Generated by Django 5.0.14 on 2025-05-19 16:16
=======
# Generated by Django 5.0.14 on 2025-04-27 18:33
>>>>>>> 3d4f397a324450a04a362f7d9feb23d25a1b81ea

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('cursos', '0001_initial'),
        ('estudiantes', '0001_initial'),
        ('usuarios', '0001_initial'),
=======
        ('docentes', '0001_initial'),
        ('inscripciones', '0001_initial'),
>>>>>>> 3d4f397a324450a04a362f7d9feb23d25a1b81ea
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('fecha', models.DateField()),
                ('tipo_evaluacion', models.CharField(choices=[('participacion', 'Participación'), ('oral', 'Oral'), ('tarea', 'Tarea'), ('mensual', 'Mensual'), ('final', 'Final')], max_length=50)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacion', models.CharField(max_length=255)),
                ('gestion', models.CharField(max_length=10)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
=======
                ('parcial1', models.FloatField()),
                ('parcial2', models.FloatField()),
                ('examen_final', models.FloatField()),
                ('promedio', models.FloatField()),
                ('id_docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.CASCADE, to='docentes.docente')),
                ('id_inscripcion', models.ForeignKey(db_column='id_inscripcion', on_delete=django.db.models.deletion.CASCADE, to='inscripciones.inscripcion')),
            ],
            options={
                'db_table': 'nota',
            },
>>>>>>> 3d4f397a324450a04a362f7d9feb23d25a1b81ea
        ),
    ]
