# Generated by Django 4.2.11 on 2025-05-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_remove_curso_asignatura_asignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='dias',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado')], max_length=20),
        ),
    ]
