# Generated by Django 4.2.11 on 2025-05-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_curso_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='dias',
            field=models.CharField(max_length=150),
        ),
    ]
