# Generated by Django 5.0.14 on 2025-05-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_inscripcion_medio_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo_estudiante',
            field=models.CharField(choices=[('tecnico', 'Técnico'), ('regular', 'Regular')], default='regular', max_length=10),
        ),
    ]
